stages: 
  - publish

class_catalog_to_pages:
  image: ubuntu
  stage: publish
  only:
    changes:
      - sfs-class-catalog.md
  artifacts:
    artifacts:
    when: always
    expire_in: 3 days
    paths:
      - converter/public

  script:
    # install node
    - apt install curl
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - sudo apt install nodejs
    - node -v
    - npm -v
    # convert class catalog to html
    # push class catalog to gitlab pages.