stages: 
  - publish

class_catalog_to_pages:
  image: ubuntu
  stage: publish
  only:
    changes:
      - sfs-class-catalog.md
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - converter/public

  script:
    # install node
    - mkdir -p converter/public
    - apt install curl
    - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    - sudo apt install nodejs
    - node -v
    - npm -v
    # convert class catalog to html
    - cp sfs-class-catalog.md converter/sfs-class-catalog.md
    - node converter/convert-catalog.js Class-Catalog
    # push class catalog to gitlab pages.
#    - git fetch https://gitlab.com/sofreeus/sofreeus.gitlab.io.git
#    - cp converter/public/sfs-class-catalog.html converter/public/sofreeus.gitlab.io/sfs-class-catalog.html
#    - cd converter/public/sofreeus.gitlab.io
#    - git add . && git commit -m "automated push from gitlab.com/sofreeus/sofreeus"
#    - git push